/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SufiRouteImport } from './routes/sufi'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConcertsRouteImport } from './routes/concerts'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookIdRouteImport } from './routes/book.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SufiRoute = SufiRouteImport.update({
  id: '/sufi',
  path: '/sufi',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcertsRoute = ConcertsRouteImport.update({
  id: '/concerts',
  path: '/concerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/concerts': typeof ConcertsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/movies': typeof MoviesRoute
  '/privacy': typeof PrivacyRoute
  '/sports': typeof SportsRoute
  '/sufi': typeof SufiRoute
  '/terms': typeof TermsRoute
  '/book/$id': typeof BookIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/concerts': typeof ConcertsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/movies': typeof MoviesRoute
  '/privacy': typeof PrivacyRoute
  '/sports': typeof SportsRoute
  '/sufi': typeof SufiRoute
  '/terms': typeof TermsRoute
  '/book/$id': typeof BookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/concerts': typeof ConcertsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/movies': typeof MoviesRoute
  '/privacy': typeof PrivacyRoute
  '/sports': typeof SportsRoute
  '/sufi': typeof SufiRoute
  '/terms': typeof TermsRoute
  '/book/$id': typeof BookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/concerts'
    | '/contact'
    | '/events'
    | '/movies'
    | '/privacy'
    | '/sports'
    | '/sufi'
    | '/terms'
    | '/book/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/concerts'
    | '/contact'
    | '/events'
    | '/movies'
    | '/privacy'
    | '/sports'
    | '/sufi'
    | '/terms'
    | '/book/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/concerts'
    | '/contact'
    | '/events'
    | '/movies'
    | '/privacy'
    | '/sports'
    | '/sufi'
    | '/terms'
    | '/book/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConcertsRoute: typeof ConcertsRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  MoviesRoute: typeof MoviesRoute
  PrivacyRoute: typeof PrivacyRoute
  SportsRoute: typeof SportsRoute
  SufiRoute: typeof SufiRoute
  TermsRoute: typeof TermsRoute
  BookIdRoute: typeof BookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sufi': {
      id: '/sufi'
      path: '/sufi'
      fullPath: '/sufi'
      preLoaderRoute: typeof SufiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concerts': {
      id: '/concerts'
      path: '/concerts'
      fullPath: '/concerts'
      preLoaderRoute: typeof ConcertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConcertsRoute: ConcertsRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  MoviesRoute: MoviesRoute,
  PrivacyRoute: PrivacyRoute,
  SportsRoute: SportsRoute,
  SufiRoute: SufiRoute,
  TermsRoute: TermsRoute,
  BookIdRoute: BookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
